LAYER_NAMES = {
    "polygon": "notams_polygon",
    "point": "notams_point",
    "text_only": "notams_text_only",
    "metadata": "metadata",
    "warnings": "parse_warnings",
}

ATTR_FIELDS = [
    "id",
    "source",
    "source_id",
    "name",
    "status",
    "effective_start",
    "effective_end",
    "qcode",
    "traffic",
    "scope",
    "activity_group",
    "radius_nm",
    "latitude",
    "longitude",
    "icao_location",
    "fir",
    "lower_limit_raw",
    "upper_limit_raw",
    "lower_limit_value",
    "upper_limit_value",
    "lower_limit_unit",
    "upper_limit_unit",
    "lower_limit_reference",
    "upper_limit_reference",
    "lower_altitude_ft",
    "upper_altitude_ft",
    "geometry_quality",
    "raw_text",
    "description",
    "source_url",
    "retrieved_at",
    "parse_warning_count",
]
