STATIC_LAYER_NAMES = {
    "controlled": "controlled_airspace",
    "aerodrome": "aerodrome_zones",
    "restrictions": "airspace_restrictions",
    "radio": "radio_transponder_zones",
    "routes": "airways_routes",
    "other": "other_permanent_airspace",
    "metadata": "metadata",
    "warnings": "parse_warnings",
}

STATIC_CATEGORY_TO_LAYER = {
    "Controlled airspace": "controlled",
    "Aerodrome zones": "aerodrome",
    "Airspace restrictions": "restrictions",
    "Radio/transponder zones": "radio",
    "Airways/routes": "routes",
    "Other permanent airspace": "other",
}

STATIC_ATTR_FIELDS = [
    "id",
    "name",
    "designator",
    "airspace_type",
    "local_type",
    "category",
    "airspace_class",
    "lower_limit_raw",
    "upper_limit_raw",
    "lower_limit_value",
    "upper_limit_value",
    "lower_limit_unit",
    "upper_limit_unit",
    "lower_limit_reference",
    "upper_limit_reference",
    "lower_altitude_ft",
    "upper_altitude_ft",
    "activation_status",
    "effective_start",
    "effective_end",
    "source",
    "source_file",
    "source_effective_date",
    "remarks",
    "geometry_quality",
    "raw_properties",
    "parse_warning_count",
]
